### PR TITLE
Scott McLeod P4 Pitch

### PR DESCRIPTION
**Pull request by smcleod86**
See above

### CODE REVIEW

**Comment by MilcahHalili** [comment]
Hey Scott, do you have an ERD? Also, can you give us daily lists of tasks from today through the day before presentations? Thanks! Also, started gardening in my backyard, so I'm looking forward to using your app!

**Comment by 009Kings** [comment]
Scott, I love this idea!
I'm just going to echo Milcah in asking for what you'll be doing day to day and an ERD

**Comment by azocher** [comment]
+1 to both what @009Kings and @MilcahHalili said but really excited to see this idea be built out - but yeah, sorry, didn't include an ERD in the requirements my bad on that one. We would still like to see though just so we can help you with any scoping/questions that come up around it.

**Comment by smcleod86** [comment]
I added links that should be public. Sorry I am sucking at this rn

**Comment by MilcahHalili** [comment]
No worries! Appreciate it. I like that you're allowing yourself a full day to debug/refactor. I'd move GraphQL to a stretch goal or post-cohort self-study.

**Comment by azocher** [comment]
+1 to what @MilcahHalili said I would look into React-Bootstrap-Table (I think the current version is actually called React-Bootstrap-Table-2 or something like that?) and would use that over D3, and then if you have 100% on the app on Tuesday feel free to stretch to GraphQL + Hasura, but before then would hold off. Approving and closing out!

**Comment by 009Kings** [comment]
For scoping purposes, too, I'd have your data visualization graph be limited to only one element of what someone is tracking. That will give you a bit more breathing room as well.

**Pull request closed without merging**
