### PR TITLE
Joshua Danao

### PR DESCRIPTION
**Pull request by JoshDanao**

### CODE REVIEW

**Comment by azocher** [comment]
@AJRJ29 - this looks like a great starting point. I would like to hear from you on how you are planning to actually facilitate the chat (like when a user sends a new message how does the other person receive it/see a new message?). A lot of the time websocket technology is used to solve this problem - have you looked into those at all or do you have another idea for how to facilitate?

**Comment by 009Kings** [comment]
I agree with Anna, what are you going to use for the chat? React Native might be enough of a new tech, maybe limit it to getting a Kanye quote or something

**Comment by JoshDanao** [comment]
So I'm thinking of using socket.io for the chat. I'm looking at the docs and watching tutorial on how to use it right now.

**Comment by azocher** [comment]
Sounds good @AJRJ29 - I would say aim for making a react native app that has a chat frontend but the actual chat data doesn't do anything/go anywhere, and then stretch goal to include in socket for chat functionality.

**Pull request closed without merging**
