### PR TITLE
Paul Padian

### PR DESCRIPTION
**Pull request by paulpadian**

### CODE REVIEW

**Comment by azocher** [comment]
@paulpadian this looks awesome! super excited to see what you are able to build. Approved on my end tagging @009Kings @nickubed and Milcah for further feedback!

**Comment by nickubed** [comment]
Very much seconding @azocher , this looks excellent!

**Comment by 009Kings** [comment]
Not gonna lie, this is ambitious for p4. I did an app similar to this for p3; we had three devs and 9 days and we BARELY got it done. To scale back, I'd have reduce the models (User, Teacher, Student, Assignment, Comment), have the submission just be a link (that can be saved as a field in Assignment), and focus primarily on the teacher side (giving comments). 
Your ERD right now is messy and doesn't make much sense (why is there a table called 'Class_id' and why does it have a field called 'Class_id' instead of just 'id'? One class has one assignment and one assignment has many classes?). I think clearing that up will help inform the rest of the user flow, but I'd defos take it down a bit.

**Comment by azocher** [comment]
@paulpadian let us know your thoughts on @009Kings feedback and we will go from there

**Comment by azocher** [comment]
@paulpadian new resubmit looks good to me - @009Kings thoughts?

**Pull request closed without merging**
