### PR TITLE
Charles Perry

### PR DESCRIPTION
**Pull request by CharlesHPerry**

### CODE REVIEW

**Comment by azocher** [comment]
@CharlesHPerry this looks good to me. I don't know enough about VR scoping to know how doable this is, but excited to see what you come up with. Tagging @009Kings @nickubed @MilcahHalili for any additional feedback!

**Comment by MilcahHalili** [comment]
I don't know enough about VR scoping as well. Would love to see your daily tasks outlined in your markdown or Trello board.

**Comment by azocher** [comment]
@CharlesHPerry send us an update with the daily task breakdown and then we can finalize approval!

**Comment by 009Kings** [comment]
My theory is that this is very overscoped. I would have your MVP be either pick an object OR change the color of an object and make everything else stretch goals.

**Comment by CharlesHPerry** [comment]
My first priority for the game will be the ability to place in the various objects into the game world, then making a physics object or two for the player to interact with. Preferably a glass pane and a ball to throw through it.

**Comment by azocher** [comment]
@CharlesHPerry sounds good - I think this is a good starting point. Excited to see what you come up with!

**Pull request closed without merging**
