### PR TITLE
Zack and da Boizz 2.0

### PR DESCRIPTION
**Pull request by Nhvattum**

### CODE REVIEW

**Comment by MilcahHalili** [comment]
Excited to see y'all working together! Can you flush out your day-by-day to-do's, please?

**Comment by MilcahHalili** [comment]
Glad to see that making fun of Josh is a priority lmao

Looks good to me!

**Comment by 009Kings** [comment]
Hey y'all! This looks great! I would move either chat or typescript to stretch goals, That is a lot to take on in 5 days, even for three devs.

**Comment by azocher** [comment]
Off what @009Kings and what @MilcahHalili said will you send in an update that scales back goals a tiny bit based on feedback above?

**Comment by azocher** [comment]
@Nhvattum I still think this is pretty ambitious for a team project, but excited to see you all push yourselves to get there. You all did great work on hackathon, so excited to see what you come up with. Approving and closing out!

**Pull request closed without merging**
