### PR TITLE
Eliott Davidson

### PR DESCRIPTION
**Pull request by fussypuppet**

### CODE REVIEW

**Comment by azocher** [comment]
@fussypuppet love the idea, and excited to see you working with UX directly! Of flutter vs react native, is there one that you are more excited to work with over the other? I think you should pick that one and dive in head first.

**Comment by MilcahHalili** [comment]
Yes, love this idea as well! Plus one to Anna's comment. Otherwise, looks great and properly scoped.

**Comment by 009Kings** [comment]
I'm just going to echo Anna and Milcah, pick whichever one you are most excited about. Make sure you you also have documentation for implementing a map and accessing a users' camera.

**Comment by fussypuppet** [comment]
Thanks for the feedback!  I'll go with Flutter

**Comment by azocher** [comment]
Sounds good @fussypuppet - you are approved to go forward. Of the devs, @009Kings is going to be the best to reach out to with any flutter questions (@nickubed @MilcahHalili add on here if you have flutter experience as well!)

**Pull request closed without merging**
