### PR TITLE
Dave Stach

### PR DESCRIPTION
**Pull request by d4vves**

### CODE REVIEW

**Comment by azocher** [comment]
@d4vves love this idea! I also would encourage you to look at other visualization libraries/animations libraries (D3 might just be more than you would need, unless you want to incorporate other bars charts/graphs), but also D3 would work great. Excited to see final app - I also keep obsessive records of how I spent my time, and would love something like this to use with my pomodoro records. @nickubed @009Kings @MilcahHalili any additional feedback?

**Comment by nickubed** [comment]
I'm excited to see how you overcome the roadblocks you had mentioned! This sounds like a super fun project!!

**Comment by 009Kings** [comment]
Love this idea! I'm sure I suggested this to you in slack, but I'll formalize it here: I'd drop the mongodb database for the scope of the project and just get CRUD working on a global variable or a json file (think dinos and crypids ala unit 2).

**Comment by azocher** [comment]
@d4vves - I'm closing out the pull request and giving you formal approval post convo with dev team in Slack!

**Pull request closed without merging**
