### PR TITLE
First pitch finally done

### PR DESCRIPTION
**Pull request by jamo1998**

### CODE REVIEW

**Comment by azocher** [comment]
@jamo1998 will you resubmit with a link to either a trello board or just breakdown in your markdown for what you are going to work on each day?

**Comment by azocher** [comment]
@jamo1998 will you add through Wednesday?

**Comment by 009Kings** [comment]
@jamo1998 What Anna said.

**Comment by azocher** [comment]
@jamo1998 I would like to see you add on some sort of additional feature for MVP, but closing out and approving. Just think of an extra stretch feature to really add a wow factor to your app.

**Pull request closed without merging**
