### PR TITLE
Nesso

### PR DESCRIPTION
**Pull request by nessoaf**

### CODE REVIEW

**Comment by azocher** [comment]
@nessoaf - I think this looks good, but will expect to see a pull request on Sunday when you have an additional idea of what you will need to work on Sunday/Monday/Tuesday as you move forward on project. Tagging @MilcahHalili @009Kings @nickubed for any additional feedback!

**Comment by nickubed** [comment]
I'm thinking getting the UI to change color / scale won't take too long, so I'm really excited to see how this gets fleshed out and what stretch-goals get added. The raid combat encounters feature sounds like an excellent, challenging project to me!

**Comment by 009Kings** [comment]
I agree with @azocher, I'd want another PR on Sunday when you have a clearer idea of how challenging it will be to learn this language and implement the simple UI color change.

**Comment by azocher** [comment]
@nessoaf we will be on the lookout for a second pull request on Sunday, but approving this idea and closing out this pull request for now.

**Pull request closed without merging**
