### PR TITLE
Jennifer De Phillips

### PR DESCRIPTION
**Pull request by jdephil**

### CODE REVIEW

**Comment by azocher** [comment]
@jdephil will you make your trello board public so we can look at it?

**Comment by 009Kings** [comment]
@jdephil, I like the idea, but I'd like a little more of it fleshed out. What does it mean for this to be interactive? How will people interact with it? Is it a story? Like a web-picture-book?

**Comment by jdephil** [comment]
my bad, just changed it!

**Comment by 009Kings** [comment]
Based on this, it might be more beneficial for you to learn an animation framework rather than sass.
Here's an article with a few that would work:
https://blog.bitsrc.io/11-javascript-animation-libraries-for-2018-9d7ac93a2c59

**Comment by jdephil** [comment]
@009Kings It's kind of like a page with a big cloud on it, you click the cloud and see the droplets forming, you can make them bigger and then eventually it starts to rain, you see the rain going into the lake. there's also some text explaining the process. etc until all the water cycle is complete. if that makes sense.

**Comment by jdephil** [comment]
an animation framework is a really good idea! i tried to teach myself one a couple of weeks ago and didn't have the time so will this is perfect

**Comment by azocher** [comment]
Awesome - I'm going to go ahead and approve @jdephil just make sure you stay on top of it for scope, but I think this will be awesome.

**Pull request closed without merging**
