### PR TITLE
Eric Young p4 pitch

### PR DESCRIPTION
**Pull request by Eryoung-610**

### CODE REVIEW

**Comment by nickubed** [comment]
I'm excited about this. Looks like a really great project idea, and I think it's within your skills to make it happen!

**Comment by azocher** [comment]
@Eryoung-610 I like the idea for this project overall, but think this is a few too many new technologies for you to work on before Wednesday. Also - which stock/data API are you thinking of using? Maybe you mentioned in README and I just didn't notice.

**Comment by Eryoung-610** [comment]
Perhaps I'll stick with angular and canvasjs? 

Forgot to mention that the API in use will be :  https://www.alphavantage.co/

On a side question, would establishing a mongo backend be ideal within the time frame? As of now, I'm not entirely sure if a backend would be needed but I also don't see it as a problem to implement, just the time frame/commitment dedicated towards a backend is something I could see as an issue.

**Comment by 009Kings** [comment]
I'm with Anna, I think this might be a few too many technologies. I would take out whichever one you are least passionate about. I also want to make sure that you've gotten data from the API that you'll be using.
Other than that, looks good.

**Comment by azocher** [comment]
@Eryoung-610 I would start building this weekend, and if you have time to build stuff out in canvasjs then awesome, but I won't hold you to it. 

Closing out this pull request and approving project - good luck!

**Pull request closed without merging**
