### PR TITLE
Michela-P4-Pitch

### PR DESCRIPTION
**Pull request by michelai95**
I'm planning on mapping out a higher def. wireframe upon approval! Please let me know if I need to rethink any of my goals. 

Thank you!

### CODE REVIEW

**Comment by nickubed** [comment]
This sounds like a super cool project! As a celiac, I'm excited to use this fascinating app 😜
Seems to have a good overlap of ambition and attainability, I think this is a great idea!

**Comment by azocher** [comment]
@michelai95 - this looks great! closing out and approving!

**Comment by 009Kings** [comment]
@michelai95 I know @azocher  closed this, but I want to double check a couple things:
 In your tech is says React and Vue. You can't really use both. I'm assuming that you're using Vue since you mentioned it later.
Secondly, have you gotten data back from your api? (Have an API-key, have been able to get a json response back)

**Comment by michelai95** [comment]
Yes, meant to be using Vue instead of React (thank you for catching that.) Yeah, already have my access-token and have run a test route to confirm that it's not as crazy of an API as Spotify! 🤦🏽‍♀️

**Pull request closed without merging**
