### PR TITLE
PITCH by emily

### PR DESCRIPTION
**Pull request by Emily-Rose-K**

### CODE REVIEW

**Comment by azocher** [comment]
Hi @Emily-Rose-K ! This looks great, and excited to see your final project. Tagging @nickubed @009Kings and @MilcahHalili to have them pass any additional feedback, but overall this looks like a great project idea.

**Comment by nickubed** [comment]
This is fantastic, I'm super excited to spend my billions on helmets for my dog

**Comment by 009Kings** [comment]
This looks good! I'm a little concerned about implementing Stripe AND Auth for RoR; I know you said you'd worked with Rails in the past, do you have a pre-existing Auth you can pull in? If not, I'd mock up the auth for p4 completion.

**Comment by Emily-Rose-K** [comment]
@009Kings totally fair - I was gonna use this http://railscasts.com/episodes/250-authentication-from-scratch-revised

If I run into problems I can def cheese it.

**Comment by azocher** [comment]
Looking good, @Emily-Rose-K ! Closing this pull request - you have been approved.

**Pull request closed without merging**
